#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with localhost 127.0.0.2 and facebook 8.8.8.8
sudo sed -i -e "s/127.0.0.1/127.0.0.2/g" /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts