#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with localhost 127.0.0.2 and facebook 8.8.8.8

grep -v "localhost" /etc/hosts > /tmp/hosts
grep -v "facebook.com" /tmp/hosts > /tmp/hosts2

echo "127.0.0.2 localhost" >> /tmp/hosts2
echo "8.8.8.8 facebook.com" >> /tmp/hosts2

cat /tmp/hosts2 > /etc/hosts