#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with localhost 127.0.0.2 and facebook 8.8.8.8

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts